export const PERFORMANCE_AUDIT = {
  PERFORMANCE_CYCLE_CREATED: 'PERFORMANCE_CYCLE_CREATED',
  PERFORMANCE_CYCLE_UPDATED: 'PERFORMANCE_CYCLE_UPDATED',
  PERFORMANCE_CYCLE_ACTIVATED: 'PERFORMANCE_CYCLE_ACTIVATED',
  PERFORMANCE_CYCLE_CLOSED: 'PERFORMANCE_CYCLE_CLOSED',
  PERFORMANCE_CYCLE_CANCELLED: 'PERFORMANCE_CYCLE_CANCELLED',
  COMPETENCY_CREATED: 'COMPETENCY_CREATED',
  COMPETENCY_UPDATED: 'COMPETENCY_UPDATED',
  COMPETENCY_SCALE_CREATED: 'COMPETENCY_SCALE_CREATED',
  COMPETENCY_SCALE_UPDATED: 'COMPETENCY_SCALE_UPDATED',
  COMPETENCY_SCALE_LEVEL_CREATED: 'COMPETENCY_SCALE_LEVEL_CREATED',
  COMPETENCY_SCALE_LEVEL_UPDATED: 'COMPETENCY_SCALE_LEVEL_UPDATED',
  COMPETENCY_SCALE_LEVEL_REMOVED: 'COMPETENCY_SCALE_LEVEL_REMOVED',
  CYCLE_COMPETENCY_ADDED: 'CYCLE_COMPETENCY_ADDED',
  CYCLE_COMPETENCY_UPDATED: 'CYCLE_COMPETENCY_UPDATED',
  CYCLE_COMPETENCY_REMOVED: 'CYCLE_COMPETENCY_REMOVED',
  PERFORMANCE_PARTICIPANT_ADDED: 'PERFORMANCE_PARTICIPANT_ADDED',
  PERFORMANCE_PARTICIPANT_EXCLUDED: 'PERFORMANCE_PARTICIPANT_EXCLUDED',
  PERFORMANCE_EVALUATION_CREATED: 'PERFORMANCE_EVALUATION_CREATED',
  PERFORMANCE_EVALUATION_RESPONSE_SAVED:
    'PERFORMANCE_EVALUATION_RESPONSE_SAVED',
  PERFORMANCE_EVALUATION_SUBMITTED: 'PERFORMANCE_EVALUATION_SUBMITTED',
  PERFORMANCE_RESULT_CALCULATED: 'PERFORMANCE_RESULT_CALCULATED',
  PERFORMANCE_RESULT_RELEASED: 'PERFORMANCE_RESULT_RELEASED',
} as const;

export const DEFAULT_PAGE = 1;
export const DEFAULT_LIMIT = 20;
export const MAX_LIMIT = 100;

/** Max length for evaluation response comments. */
export const EVALUATION_COMMENT_MAX_LENGTH = 2000;

/** Minimum scale levels required to activate a cycle. */
export const MIN_SCALE_LEVELS_FOR_ACTIVATION = 2;

/** Expected total when any cycle competency uses weight. */
export const WEIGHT_TOTAL_REQUIRED = 100;
