export const GOALS_AUDIT = {
  GOAL_CYCLE_CREATED: 'GOAL_CYCLE_CREATED',
  GOAL_CYCLE_UPDATED: 'GOAL_CYCLE_UPDATED',
  GOAL_CYCLE_ACTIVATED: 'GOAL_CYCLE_ACTIVATED',
  GOAL_CYCLE_CLOSED: 'GOAL_CYCLE_CLOSED',
  GOAL_CYCLE_CANCELLED: 'GOAL_CYCLE_CANCELLED',
  GOAL_CREATED: 'GOAL_CREATED',
  GOAL_UPDATED: 'GOAL_UPDATED',
  GOAL_ACTIVATED: 'GOAL_ACTIVATED',
  GOAL_CANCELLED: 'GOAL_CANCELLED',
  GOAL_KEY_RESULT_CREATED: 'GOAL_KEY_RESULT_CREATED',
  GOAL_KEY_RESULT_UPDATED: 'GOAL_KEY_RESULT_UPDATED',
  GOAL_KEY_RESULT_DELETED: 'GOAL_KEY_RESULT_DELETED',
  GOAL_ASSIGNMENT_ADDED: 'GOAL_ASSIGNMENT_ADDED',
  GOAL_ASSIGNMENT_REMOVED: 'GOAL_ASSIGNMENT_REMOVED',
  GOAL_CHECK_IN_CREATED: 'GOAL_CHECK_IN_CREATED',
  GOAL_COMPLETION_REQUESTED: 'GOAL_COMPLETION_REQUESTED',
  GOAL_COMPLETION_REJECTED: 'GOAL_COMPLETION_REJECTED',
  GOAL_COMPLETION_APPROVED: 'GOAL_COMPLETION_APPROVED',
  GOAL_COMPLETED: 'GOAL_COMPLETED',
  GOAL_RESULT_CREATED: 'GOAL_RESULT_CREATED',
} as const;

export const DEFAULT_PAGE = 1;
export const DEFAULT_LIMIT = 20;
export const MAX_LIMIT = 100;
export const WEIGHT_TOTAL_REQUIRED = 100;
