import { ConflictException } from '@nestjs/common';
import { Prisma } from '@prisma/client';

export const DUPLICATE_COMPANY_CODE_MODELS = [
  'BusinessUnit',
  'Area',
  'JobLevel',
  'Position',
  'Competency',
] as const;

export type DuplicateCompanyCodeModel =
  (typeof DUPLICATE_COMPANY_CODE_MODELS)[number];

const RESOURCE_PHRASE: Record<DuplicateCompanyCodeModel, string> = {
  BusinessUnit: 'una unidad de negocio',
  Area: 'un área',
  JobLevel: 'un nivel de cargo',
  Position: 'un cargo',
  Competency: 'una competencia',
};

/** PostgreSQL unique index names generated by Prisma for companyId+code. */
const CONSTRAINT_TO_MODEL: Record<string, DuplicateCompanyCodeModel> = {
  business_units_companyId_code_key: 'BusinessUnit',
  areas_companyId_code_key: 'Area',
  job_levels_companyId_code_key: 'JobLevel',
  positions_companyId_code_key: 'Position',
  competencies_companyId_code_key: 'Competency',
};

const MODEL_SET = new Set<string>(DUPLICATE_COMPANY_CODE_MODELS);

export function sanitizeCodeForMessage(code: unknown): string | null {
  if (typeof code !== 'string') return null;
  const trimmed = code.trim();
  if (!trimmed || trimmed.length > 64) return null;
  for (const char of trimmed) {
    if (char.charCodeAt(0) < 32) return null;
  }
  return trimmed;
}

export function formatDuplicateCompanyCodeMessage(
  model: DuplicateCompanyCodeModel,
  code?: string | null,
): string {
  const resource = RESOURCE_PHRASE[model];
  const safe = sanitizeCodeForMessage(code);
  if (safe) {
    return `Ya existe ${resource} con el código ${safe}.`;
  }
  return `Ya existe ${resource} con ese código.`;
}

export function resolveDuplicateCompanyCodeModel(
  error: Prisma.PrismaClientKnownRequestError,
): DuplicateCompanyCodeModel | null {
  const meta = error.meta ?? {};
  const target = meta.target;
  const modelName = typeof meta.modelName === 'string' ? meta.modelName : null;

  if (typeof target === 'string') {
    return CONSTRAINT_TO_MODEL[target] ?? null;
  }

  const fields = Array.isArray(target)
    ? target.filter((field): field is string => typeof field === 'string')
    : [];
  const isCompanyCode =
    fields.length === 2 &&
    fields.includes('companyId') &&
    fields.includes('code');
  if (!isCompanyCode) {
    return null;
  }
  if (modelName && MODEL_SET.has(modelName)) {
    return modelName as DuplicateCompanyCodeModel;
  }
  return null;
}

export function duplicateCompanyCodeMessage(
  error: unknown,
  attemptedCode?: string | null,
): string | null {
  if (
    !(error instanceof Prisma.PrismaClientKnownRequestError) ||
    error.code !== 'P2002'
  ) {
    return null;
  }
  const model = resolveDuplicateCompanyCodeModel(error);
  if (!model) return null;
  return formatDuplicateCompanyCodeMessage(model, attemptedCode);
}

export function rethrowDuplicateCompanyCodeConflict(
  error: unknown,
  attemptedCode?: string | null,
): never {
  const message = duplicateCompanyCodeMessage(error, attemptedCode);
  if (message) {
    throw new ConflictException(message);
  }
  throw error;
}

export async function withDuplicateCompanyCodeConflict<T>(
  attemptedCode: string | null | undefined,
  work: () => Promise<T>,
): Promise<T> {
  try {
    return await work();
  } catch (error) {
    rethrowDuplicateCompanyCodeConflict(error, attemptedCode);
  }
}

export function attemptedCodeFromRequestBody(body: unknown): string | null {
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    return null;
  }
  return sanitizeCodeForMessage((body as { code?: unknown }).code);
}
