import { ConflictException } from '@nestjs/common';
import { Prisma } from '@prisma/client';

export const DUPLICATE_COMPANY_CODE_MODELS = [
  'BusinessUnit',
  'Area',
  'JobLevel',
  'Position',
  'Competency',
] as const;

export type DuplicateCompanyCodeModel =
  (typeof DUPLICATE_COMPANY_CODE_MODELS)[number];

const RESOURCE_PHRASE: Record<DuplicateCompanyCodeModel, string> = {
  BusinessUnit: 'una unidad de negocio',
  Area: 'un área',
  JobLevel: 'un nivel de cargo',
  Position: 'un cargo',
  Competency: 'una competencia',
};

/** PostgreSQL unique index names generated by Prisma for companyId+code. */
const CODE_CONSTRAINT_TO_MODEL: Record<string, DuplicateCompanyCodeModel> = {
  business_units_companyId_code_key: 'BusinessUnit',
  areas_companyId_code_key: 'Area',
  job_levels_companyId_code_key: 'JobLevel',
  positions_companyId_code_key: 'Position',
  competencies_companyId_code_key: 'Competency',
};

const NAME_CONSTRAINT_TO_MODEL: Record<string, DuplicateCompanyCodeModel> = {
  business_units_companyId_name_key: 'BusinessUnit',
  areas_companyId_name_key: 'Area',
  job_levels_companyId_name_key: 'JobLevel',
  positions_companyId_name_key: 'Position',
  competencies_companyId_name_key: 'Competency',
};

const RANK_CONSTRAINTS = new Set(['job_levels_companyId_rank_key']);

const MODEL_SET = new Set<string>(DUPLICATE_COMPANY_CODE_MODELS);

export function sanitizeCodeForMessage(code: unknown): string | null {
  if (typeof code !== 'string') return null;
  const trimmed = code.trim();
  if (!trimmed || trimmed.length > 64) return null;
  for (const char of trimmed) {
    if (char.charCodeAt(0) < 32) return null;
  }
  return trimmed;
}

export function formatDuplicateCompanyCodeMessage(
  model: DuplicateCompanyCodeModel,
  code?: string | null,
): string {
  const resource = RESOURCE_PHRASE[model];
  const safe = sanitizeCodeForMessage(code);
  if (safe) {
    return `Ya existe ${resource} con el código ${safe}.`;
  }
  return `Ya existe ${resource} con ese código.`;
}

export function formatDuplicateCompanyNameMessage(
  model: DuplicateCompanyCodeModel,
  name?: string | null,
): string {
  const resource = RESOURCE_PHRASE[model];
  const safe = sanitizeCodeForMessage(name);
  if (safe) {
    return `Ya existe ${resource} con el nombre ${safe}.`;
  }
  return `Ya existe ${resource} con ese nombre.`;
}

function constraintNameFromTarget(target: unknown): string | null {
  if (typeof target === 'string') return target;
  if (
    Array.isArray(target) &&
    target.length === 1 &&
    typeof target[0] === 'string' &&
    (target[0].includes('_key') || target[0].includes('_idx'))
  ) {
    return target[0];
  }
  return null;
}

function fieldNamesFromTarget(target: unknown): string[] {
  if (!Array.isArray(target)) return [];
  return target.filter((field): field is string => typeof field === 'string');
}

function hasCompanyField(
  fields: string[],
  field: 'code' | 'name' | 'rank',
): boolean {
  return (
    fields.length === 2 &&
    fields.includes('companyId') &&
    fields.includes(field)
  );
}

export function resolveDuplicateCompanyCodeModel(
  error: Prisma.PrismaClientKnownRequestError,
): DuplicateCompanyCodeModel | null {
  const meta = error.meta ?? {};
  const target = meta.target;
  const modelName = typeof meta.modelName === 'string' ? meta.modelName : null;
  const constraint = constraintNameFromTarget(target);
  if (constraint && CODE_CONSTRAINT_TO_MODEL[constraint]) {
    return CODE_CONSTRAINT_TO_MODEL[constraint];
  }

  const fields = fieldNamesFromTarget(target);
  if (!hasCompanyField(fields, 'code')) {
    return null;
  }
  if (modelName && MODEL_SET.has(modelName)) {
    return modelName as DuplicateCompanyCodeModel;
  }
  return null;
}

function resolveDuplicateCompanyNameModel(
  error: Prisma.PrismaClientKnownRequestError,
): DuplicateCompanyCodeModel | null {
  const meta = error.meta ?? {};
  const target = meta.target;
  const modelName = typeof meta.modelName === 'string' ? meta.modelName : null;
  const constraint = constraintNameFromTarget(target);
  if (constraint && NAME_CONSTRAINT_TO_MODEL[constraint]) {
    return NAME_CONSTRAINT_TO_MODEL[constraint];
  }

  const fields = fieldNamesFromTarget(target);
  if (!hasCompanyField(fields, 'name')) {
    return null;
  }
  if (modelName && MODEL_SET.has(modelName)) {
    return modelName as DuplicateCompanyCodeModel;
  }
  return null;
}

function isJobLevelRankConflict(
  error: Prisma.PrismaClientKnownRequestError,
): boolean {
  const meta = error.meta ?? {};
  const constraint = constraintNameFromTarget(meta.target);
  if (constraint && RANK_CONSTRAINTS.has(constraint)) return true;
  const fields = fieldNamesFromTarget(meta.target);
  return hasCompanyField(fields, 'rank');
}

export function duplicateCompanyCodeMessage(
  error: unknown,
  attemptedCode?: string | null,
): string | null {
  if (
    !(error instanceof Prisma.PrismaClientKnownRequestError) ||
    error.code !== 'P2002'
  ) {
    return null;
  }
  const model = resolveDuplicateCompanyCodeModel(error);
  if (!model) return null;
  return formatDuplicateCompanyCodeMessage(model, attemptedCode);
}

export function duplicateOrgUniqueMessage(
  error: unknown,
  attempted?: { code?: string | null; name?: string | null },
): string | null {
  if (
    !(error instanceof Prisma.PrismaClientKnownRequestError) ||
    error.code !== 'P2002'
  ) {
    return null;
  }
  const codeModel = resolveDuplicateCompanyCodeModel(error);
  if (codeModel) {
    return formatDuplicateCompanyCodeMessage(codeModel, attempted?.code);
  }
  const nameModel = resolveDuplicateCompanyNameModel(error);
  if (nameModel) {
    return formatDuplicateCompanyNameMessage(nameModel, attempted?.name);
  }
  if (isJobLevelRankConflict(error)) {
    return 'Ya existe un nivel de cargo con ese rango.';
  }
  return null;
}

export function rethrowDuplicateCompanyCodeConflict(
  error: unknown,
  attemptedCode?: string | null,
  attemptedName?: string | null,
): never {
  const message = duplicateOrgUniqueMessage(error, {
    code: attemptedCode,
    name: attemptedName,
  });
  if (message) {
    throw new ConflictException(message);
  }
  throw error;
}

export async function withDuplicateCompanyCodeConflict<T>(
  attemptedCode: string | null | undefined,
  work: () => Promise<T>,
  attemptedName?: string | null,
): Promise<T> {
  try {
    return await work();
  } catch (error) {
    rethrowDuplicateCompanyCodeConflict(error, attemptedCode, attemptedName);
  }
}

export function attemptedCodeFromRequestBody(body: unknown): string | null {
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    return null;
  }
  return sanitizeCodeForMessage((body as { code?: unknown }).code);
}

export function attemptedNameFromRequestBody(body: unknown): string | null {
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    return null;
  }
  return sanitizeCodeForMessage((body as { name?: unknown }).name);
}
