export const ORG_AUDIT = {
  BUSINESS_UNIT_CREATED: 'BUSINESS_UNIT_CREATED',
  BUSINESS_UNIT_UPDATED: 'BUSINESS_UNIT_UPDATED',
  AREA_CREATED: 'AREA_CREATED',
  AREA_UPDATED: 'AREA_UPDATED',
  JOB_LEVEL_CREATED: 'JOB_LEVEL_CREATED',
  JOB_LEVEL_UPDATED: 'JOB_LEVEL_UPDATED',
  JOB_LEVEL_COMPETENCIES_UPDATED: 'JOB_LEVEL_COMPETENCIES_UPDATED',
  POSITION_CREATED: 'POSITION_CREATED',
  POSITION_UPDATED: 'POSITION_UPDATED',
  POSITION_CUSTOM_FIELD_DEFINITION_CREATED:
    'POSITION_CUSTOM_FIELD_DEFINITION_CREATED',
  POSITION_CUSTOM_FIELD_DEFINITION_UPDATED:
    'POSITION_CUSTOM_FIELD_DEFINITION_UPDATED',
  POSITION_CUSTOM_FIELDS_UPDATED: 'POSITION_CUSTOM_FIELDS_UPDATED',
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  REPORTING_LINE_CREATED: 'REPORTING_LINE_CREATED',
  REPORTING_LINE_REMOVED: 'REPORTING_LINE_REMOVED',
} as const;

export const DEFAULT_PAGE = 1;
export const DEFAULT_LIMIT = 20;
export const MAX_LIMIT = 100;
