export const ATS_AUDIT = {
  VACANCY_REQUEST_CREATED: 'VACANCY_REQUEST_CREATED',
  VACANCY_REQUEST_UPDATED: 'VACANCY_REQUEST_UPDATED',
  VACANCY_REQUEST_SUBMITTED: 'VACANCY_REQUEST_SUBMITTED',
  VACANCY_REQUEST_APPROVED_STEP: 'VACANCY_REQUEST_APPROVED_STEP',
  VACANCY_REQUEST_REJECTED: 'VACANCY_REQUEST_REJECTED',
  VACANCY_REQUEST_APPROVED: 'VACANCY_REQUEST_APPROVED',
  VACANCY_CREATED: 'VACANCY_CREATED',
  VACANCY_STATUS_CHANGED: 'VACANCY_STATUS_CHANGED',
  CANDIDATE_CREATED: 'CANDIDATE_CREATED',
  CANDIDATE_UPDATED: 'CANDIDATE_UPDATED',
  APPLICATION_CREATED: 'APPLICATION_CREATED',
  APPLICATION_STAGE_CHANGED: 'APPLICATION_STAGE_CHANGED',
  INTERVIEW_CREATED: 'INTERVIEW_CREATED',
  INTERVIEW_UPDATED: 'INTERVIEW_UPDATED',
  INTERVIEW_STARTED: 'INTERVIEW_STARTED',
  INTERVIEW_COMPLETED: 'INTERVIEW_COMPLETED',
  INTERVIEW_CANCELLED: 'INTERVIEW_CANCELLED',
  INTERVIEW_ANSWER_SAVED: 'INTERVIEW_ANSWER_SAVED',
  TRANSCRIPT_SEGMENT_CREATED: 'TRANSCRIPT_SEGMENT_CREATED',
  TRANSCRIPT_SEGMENT_UPDATED: 'TRANSCRIPT_SEGMENT_UPDATED',
  TRANSCRIPT_SEGMENT_REMOVED: 'TRANSCRIPT_SEGMENT_REMOVED',
  INTERVIEW_TEMPLATE_CREATED: 'INTERVIEW_TEMPLATE_CREATED',
  INTERVIEW_TEMPLATE_UPDATED: 'INTERVIEW_TEMPLATE_UPDATED',
  OFFER_CREATED: 'OFFER_CREATED',
  OFFER_UPDATED: 'OFFER_UPDATED',
  OFFER_SENT: 'OFFER_SENT',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  OFFER_REJECTED: 'OFFER_REJECTED',
  OFFER_WITHDRAWN: 'OFFER_WITHDRAWN',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  HIRING_COMPLETED: 'HIRING_COMPLETED',
} as const;

export const DEFAULT_PAGE = 1;
export const DEFAULT_LIMIT = 20;
export const MAX_LIMIT = 100;

/** Temporary role used for HR and General Manager approval steps. */
export const TEMP_APPROVER_ROLE_CODE = 'CLIENT_ADMIN';

export const PROXY_REQUESTER_ROLE_CODES = [
  'CLIENT_ADMIN',
  'RECRUITER',
] as const;

/** User-facing requester errors (Spanish). Do not include tenant or employee ids. */
export const VACANCY_REQUESTER_ERRORS = {
  SELECT_REQUESTER: 'Selecciona el colaborador que realiza la solicitud.',
  NO_LINKED_EMPLOYEE:
    'Tu usuario no tiene un colaborador asociado. Contacta al administrador de la compañía.',
  CANNOT_PROXY: 'No puedes crear solicitudes en nombre de otro colaborador.',
} as const;

export const PIPELINE_STAGES = [
  'PENDING_REVIEW',
  'CONTACTED',
  'INTERVIEW',
  'OFFER',
  'HIRED',
  'REJECTED',
  'WITHDRAWN',
] as const;
