export const ATS_AUDIT = {
  VACANCY_REQUEST_CREATED: 'VACANCY_REQUEST_CREATED',
  VACANCY_REQUEST_UPDATED: 'VACANCY_REQUEST_UPDATED',
  VACANCY_REQUEST_SUBMITTED: 'VACANCY_REQUEST_SUBMITTED',
  VACANCY_REQUEST_APPROVED_STEP: 'VACANCY_REQUEST_APPROVED_STEP',
  VACANCY_REQUEST_REJECTED: 'VACANCY_REQUEST_REJECTED',
  VACANCY_REQUEST_APPROVED: 'VACANCY_REQUEST_APPROVED',
  VACANCY_CREATED: 'VACANCY_CREATED',
  VACANCY_STATUS_CHANGED: 'VACANCY_STATUS_CHANGED',
} as const;

export const DEFAULT_PAGE = 1;
export const DEFAULT_LIMIT = 20;
export const MAX_LIMIT = 100;

/** Temporary role used for HR and General Manager approval steps. */
export const TEMP_APPROVER_ROLE_CODE = 'CLIENT_ADMIN';

export const PROXY_REQUESTER_ROLE_CODES = [
  'CLIENT_ADMIN',
  'RECRUITER',
] as const;
