export const ATS_AUDIT = {
  VACANCY_REQUEST_CREATED: 'VACANCY_REQUEST_CREATED',
  VACANCY_REQUEST_UPDATED: 'VACANCY_REQUEST_UPDATED',
  VACANCY_REQUEST_SUBMITTED: 'VACANCY_REQUEST_SUBMITTED',
  VACANCY_REQUEST_APPROVED_STEP: 'VACANCY_REQUEST_APPROVED_STEP',
  VACANCY_REQUEST_REJECTED: 'VACANCY_REQUEST_REJECTED',
  VACANCY_REQUEST_APPROVED: 'VACANCY_REQUEST_APPROVED',
  VACANCY_CREATED: 'VACANCY_CREATED',
  VACANCY_STATUS_CHANGED: 'VACANCY_STATUS_CHANGED',
  CANDIDATE_CREATED: 'CANDIDATE_CREATED',
  CANDIDATE_UPDATED: 'CANDIDATE_UPDATED',
  APPLICATION_CREATED: 'APPLICATION_CREATED',
  APPLICATION_STAGE_CHANGED: 'APPLICATION_STAGE_CHANGED',
  INTERVIEW_CREATED: 'INTERVIEW_CREATED',
  INTERVIEW_UPDATED: 'INTERVIEW_UPDATED',
  INTERVIEW_STARTED: 'INTERVIEW_STARTED',
  INTERVIEW_COMPLETED: 'INTERVIEW_COMPLETED',
  INTERVIEW_CANCELLED: 'INTERVIEW_CANCELLED',
  INTERVIEW_ANSWER_SAVED: 'INTERVIEW_ANSWER_SAVED',
  TRANSCRIPT_SEGMENT_CREATED: 'TRANSCRIPT_SEGMENT_CREATED',
  TRANSCRIPT_SEGMENT_UPDATED: 'TRANSCRIPT_SEGMENT_UPDATED',
  TRANSCRIPT_SEGMENT_REMOVED: 'TRANSCRIPT_SEGMENT_REMOVED',
  INTERVIEW_TEMPLATE_CREATED: 'INTERVIEW_TEMPLATE_CREATED',
  INTERVIEW_TEMPLATE_UPDATED: 'INTERVIEW_TEMPLATE_UPDATED',
} as const;

export const DEFAULT_PAGE = 1;
export const DEFAULT_LIMIT = 20;
export const MAX_LIMIT = 100;

/** Temporary role used for HR and General Manager approval steps. */
export const TEMP_APPROVER_ROLE_CODE = 'CLIENT_ADMIN';

export const PROXY_REQUESTER_ROLE_CODES = [
  'CLIENT_ADMIN',
  'RECRUITER',
] as const;

export const PIPELINE_STAGES = [
  'PENDING_REVIEW',
  'CONTACTED',
  'INTERVIEW',
  'OFFER',
  'HIRED',
  'REJECTED',
  'WITHDRAWN',
] as const;
